_base_: "default.yml"
defaults:
  - _self_

seed: 0
model_name: clip_dinoiser
model:
  type: CLIP_DINOiser
  clip_backbone: maskclip
  mask_th: 0.2
  in_dim: 256
  certainty_th: 0.9
  found_th: 0.5
  feats_idx: -3

checkpoint_path: "checkpoints/last.pt"
output: logs

evaluate:
  eval_only: true
  task:
    - voc
    - voc20
    - context
    - context59
    - coco_stuff
    - coco_object
    - cityscapes
    - ade20k

  # evaluation
  voc: segmentation/configs/_base_/datasets/pascal_voc12.py
  voc20: segmentation/configs/_base_/datasets/pascal_voc12_20.py
  context: segmentation/configs/_base_/datasets/pascal_context.py
  context59: segmentation/configs/_base_/datasets/pascal_context59.py
  coco_stuff: segmentation/configs/_base_/datasets/stuff.py
  coco_object: segmentation/configs/_base_/datasets/coco.py
  cityscapes: segmentation/configs/_base_/datasets/cityscapes.py
  ade20k: segmentation/configs/_base_/datasets/ade20k.py
